version: "3"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: dev.env
        environment:
            - PORT=8080
        ports:
            - 8081:8080
        volumes:
            - ./app:/app/
            - node_modules:/app/node_modules
            - output:/app/dist
        networks:
            - atm-sync
volumes:
    node_modules:
    output:
networks:
    atm-sync:
