version: "3"
services:
  atm-sync:
    build:
      context: atm-sync
      dockerfile: Dockerfile
    environment:
      - SOME_ENV:1
    volumes:
      - ./atm-sync:/app/
      - atm-sync_node_modules:/app/node_modules
volumes:
  atm-sync_node_modules:
